name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python train.py
          
          cat metrics.txt >> confusion.md
          cml-publish confusion_matrix.png --md --title 'Confusion Matrix' >> confusion.md
          cml-send-comment confusion.md 
