name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i -g @dvcorg/cml
          sh colormaru.sh
          cml-publish result_images/image.png --md --title 'ColorMaru' >> color.md
          cml-send-comment color.md 
