name: Color_That

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: colormaru_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo chown -R $(whoami) /usr/local/lib/node_modules
          sudo chmod -R 777 *
          npm config set unsafe-perm=true
          npm i @dvcorg/cml
          sh colormaru.sh
          cml-publish result_images/image.png --md --title 'ColorMaru' >> color.md
          cml-send-comment color.md 
