name: test_dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: dvc_npm
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #sudo chown -R $(id -u):$(id -g) /usr/local/lib/node_modules
          sudo chown -R $(whoami) /usr/local/lib/node_modules
          sudo npm i -g @dvcorg/cml
