name: test_dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: dvc_npm
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export USER = "ucalyptus"
          sudo chown -R $USER /usr/local/lib/node_modules
          npm i -g @dvcorg/cml
