name: test_dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: dvc_npm
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo chown -R $(whoami) /usr/local/lib/node_modules
          sudo chmod -R 777 *
          npm config set unsafe-perm=true
          npm i -g @dvcorg/cml
