name: test_dvc
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: dvc_npm
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: "ucalyptus"
        run: |
          sudo chown -R $GITHUB_USERNAME /usr/local/lib/node_modules
          npm i -g @dvcorg/cml
